#!/bin/bash

# Copyright (C) 2010 Eiichi Sato
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

# database
database="index.db"

# always cd to script directory
scriptpath="$(readlink -f "$0")"
scriptdir="$(dirname "$scriptpath")"
cd "$scriptdir"

# no arguments specified, or specified keyword is too short
[ $# -lt 1 ] || [ ${#1} -lt 5 ] && \
	exit 1

# try exact match
result=$(sqlite3 "$database" "SELECT path FROM tmp WHERE key = '$1' and path not like '%#%'")

# try prefix match
if [ -n "$result" ]; then
   w3m -dump -T text/html $result
else
 	echo "No documentation found."
  	exit 1
fi

