#!/bin/bash

# Copyright (C) 2010 Eiichi Sato
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

# database
database="index.db"

# always cd to script directory
scriptpath="$(readlink -f "$0")"
scriptdir="$(dirname "$scriptpath")"
cd "$scriptdir"

# no arguments specified, or specified keyword is too short
if [ $# -lt 1 ]; then
   echo "provide a query to search for"
	exit 1
fi
if [ ${#1} -lt 5 ]; then
   echo "query too short it should have more than 4 characters" 
	exit 1
fi

QUERY=$1

# try exact match
result=$(sqlite3 "$database" "SELECT path FROM tmp WHERE key = '$QUERY'")

# try prefix match
if [ -z "$result" ]; then
	result=$(sqlite3 "$database" "SELECT path FROM tmp WHERE key like '$QUERY%' ORDER BY length(key) ASC")
fi

# try method exact match
if [ -z "$result" ]; then
   METHOD=${QUERY/_/-} 
	result=$(sqlite3 "$database" "SELECT path FROM tmp WHERE key like '%.$QUERY' ORDER BY length(key) ASC")
fi

# try method match
if [ -z "$result" ]; then
   METHOD=${QUERY/_/-} 
	result=$(sqlite3 "$database" "SELECT path FROM tmp WHERE key like '%$QUERY%' ORDER BY length(key) ASC")
fi
if [ -n "$result" ]; then
   echo "$result"
else
	echo "No documentation found."
	exit 1
fi
