#!/bin/bash

# Copyright (C) 2010 Eiichi Sato
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

# no arguments
if [ $# -lt 1 ]
then
	exit
fi

# specified keyword is too short
if [ ${#1} -lt 5 ]
then
	exit
fi

SELFPATH=`realpath $0`
TOOLDIR=`dirname $SELFPATH`
cd $TOOLDIR

INDEXDB=index
TMPFILE=`mktemp`

# exact match
ROWS=`sqlite3 $INDEXDB "SELECT path FROM tmp WHERE key = '$1'"`

if [ -z "$ROWS" ]
then
	ROWS=`sqlite3 $INDEXDB "SELECT path FROM tmp WHERE key like '$1%' ORDER BY length(key) ASC"`
fi

./get $ROWS > $TMPFILE
if [ $? -eq 0 ]
then
	w3m -dump -T text/html $TMPFILE
else
	echo "No documentation found."
fi

rm $TMPFILE
