#!/bin/bash

# Copyright (C) 2010 Eiichi Sato
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

# database
database="index.db"
docdirs=('/usr/share/gtk-doc/html' '/usr/local/share/gtk-doc/html')

# always cd to script directory
scriptpath="$(readlink -f "$0")"
scriptdir="$(dirname "$scriptpath")"
cd "$scriptdir"

tmp=$(mktemp)

echo "PRAGMA foreign_keys=OFF;" >> $tmp
echo "DROP TABLE IF EXISTS tmp;" >> $tmp
echo "CREATE TABLE tmp (key TEXT, path TEXT, PRIMARY KEY (key, path));" >> $tmp
echo "BEGIN TRANSACTION;" >> $tmp

for dir in $docdirs; do
	for index in $dir/*/*.devhelp2 $dir/*/*.devhelp; do
		./cache_query $index >> $tmp
	done
done

echo "COMMIT;" >> $tmp
echo "CREATE INDEX idx_tmp_key ON tmp (key);" >> $tmp

sqlite3 "$database" < $tmp

rm $tmp
